/*
-----------------------------------------------------
SQLITEContractGen.py 2.0

This file was autogenerated with run cmd:
  "SQLITEContractGen.py --packagename=org.frc836.database --classname=FRCScoutingContract --infile=FRC_Scouting_Server/scouting.sql --outfile=app/src/main/java/org/frc836/database/FRCScoutingContract.java"

python version info:
  2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]

Please take heed of modifying unnecessarily
-----------------------------------------------------
*/

package org.frc836.database;

import android.provider.BaseColumns;

public final class FRCScoutingContract {
	public FRCScoutingContract() {}

	public static abstract class CONFIGURATION_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "configuration_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_CONFIGURATION_DESC = "configuration_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class DEFENSE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "defense_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_DEFENSE_DESC = "defense_desc";
		public static final String COLUMN_NAME_INVALID = "invalid";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}
	
	public static abstract class EVENT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "event_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_NAME = "event_name";
		public static final String COLUMN_NAME_EVENT_CODE = "event_code";
		public static final String COLUMN_NAME_DATE_START = "date_start";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class FACT_MATCH_DATA_2016_Entry implements BaseColumns {
		public static final String TABLE_NAME = "fact_match_data_2016";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_ID = "event_id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_MATCH_ID = "match_id";
		public static final String COLUMN_NAME_PRACTICE_MATCH = "practice_match";
		public static final String COLUMN_NAME_POSITION_ID = "position_id";
		public static final String COLUMN_NAME_RED_DEF_2 = "red_def_2";
		public static final String COLUMN_NAME_RED_DEF_3 = "red_def_3";
		public static final String COLUMN_NAME_RED_DEF_4 = "red_def_4";
		public static final String COLUMN_NAME_RED_DEF_5 = "red_def_5";
		public static final String COLUMN_NAME_BLUE_DEF_2 = "blue_def_2";
		public static final String COLUMN_NAME_BLUE_DEF_3 = "blue_def_3";
		public static final String COLUMN_NAME_BLUE_DEF_4 = "blue_def_4";
		public static final String COLUMN_NAME_BLUE_DEF_5 = "blue_def_5";
		public static final String COLUMN_NAME_AUTO_REACH = "auto_reach";
		public static final String COLUMN_NAME_START_SPY = "start_spy";
		public static final String COLUMN_NAME_AUTO_CROSS_PORTCULLIS_FOR = "auto_cross_portcullis_for";
		public static final String COLUMN_NAME_AUTO_CROSS_PORTCULLIS_REV = "auto_cross_portcullis_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_CHEVAL_FOR = "auto_cross_cheval_for";
		public static final String COLUMN_NAME_AUTO_CROSS_CHEVAL_REV = "auto_cross_cheval_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_MOAT_FOR = "auto_cross_moat_for";
		public static final String COLUMN_NAME_AUTO_CROSS_MOAT_REV = "auto_cross_moat_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_RAMPARTS_FOR = "auto_cross_ramparts_for";
		public static final String COLUMN_NAME_AUTO_CROSS_RAMPARTS_REV = "auto_cross_ramparts_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_DRAWBRIDGE_FOR = "auto_cross_drawbridge_for";
		public static final String COLUMN_NAME_AUTO_CROSS_DRAWBRIDGE_FOR_WITH_HELP = "auto_cross_drawbridge_for_with_help";
		public static final String COLUMN_NAME_AUTO_CROSS_DRAWBRIDGE_REV = "auto_cross_drawbridge_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_SALLY_FOR = "auto_cross_sally_for";
		public static final String COLUMN_NAME_AUTO_CROSS_SALLY_FOR_WITH_HELP = "auto_cross_sally_for_with_help";
		public static final String COLUMN_NAME_AUTO_CROSS_SALLY_REV = "auto_cross_sally_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_ROCK_WALL_FOR = "auto_cross_rock_wall_for";
		public static final String COLUMN_NAME_AUTO_CROSS_ROCK_WALL_REV = "auto_cross_rock_wall_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_ROUGH_TERRAIN_FOR = "auto_cross_rough_terrain_for";
		public static final String COLUMN_NAME_AUTO_CROSS_ROUGH_TERRAIN_REV = "auto_cross_rough_terrain_rev";
		public static final String COLUMN_NAME_AUTO_CROSS_LOW_BAR_FOR = "auto_cross_low_bar_for";
		public static final String COLUMN_NAME_AUTO_CROSS_LOW_BAR_REV = "auto_cross_low_bar_rev";
		public static final String COLUMN_NAME_AUTO_SCORE_LOW = "auto_score_low";
		public static final String COLUMN_NAME_AUTO_SCORE_HIGH = "auto_score_high";
		public static final String COLUMN_NAME_AUTO_MISS_LOW = "auto_miss_low";
		public static final String COLUMN_NAME_AUTO_MISS_HIGH = "auto_miss_high";
		public static final String COLUMN_NAME_CROSS_PORTCULLIS_FOR = "cross_portcullis_for";
		public static final String COLUMN_NAME_CROSS_PORTCULLIS_REV = "cross_portcullis_rev";
		public static final String COLUMN_NAME_CROSS_CHEVAL_FOR = "cross_cheval_for";
		public static final String COLUMN_NAME_CROSS_CHEVAL_REV = "cross_cheval_rev";
		public static final String COLUMN_NAME_CROSS_MOAT_FOR = "cross_moat_for";
		public static final String COLUMN_NAME_CROSS_MOAT_REV = "cross_moat_rev";
		public static final String COLUMN_NAME_CROSS_RAMPARTS_FOR = "cross_ramparts_for";
		public static final String COLUMN_NAME_CROSS_RAMPARTS_REV = "cross_ramparts_rev";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_FOR = "cross_drawbridge_for";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_FOR_WITH_HELP = "cross_drawbridge_for_with_help";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_REV = "cross_drawbridge_rev";
		public static final String COLUMN_NAME_CROSS_SALLY_FOR = "cross_sally_for";
		public static final String COLUMN_NAME_CROSS_SALLY_FOR_WITH_HELP = "cross_sally_for_with_help";
		public static final String COLUMN_NAME_CROSS_SALLY_REV = "cross_sally_rev";
		public static final String COLUMN_NAME_CROSS_ROCK_WALL_FOR = "cross_rock_wall_for";
		public static final String COLUMN_NAME_CROSS_ROCK_WALL_REV = "cross_rock_wall_rev";
		public static final String COLUMN_NAME_CROSS_ROUGH_TERRAIN_FOR = "cross_rough_terrain_for";
		public static final String COLUMN_NAME_CROSS_ROUGH_TERRAIN_REV = "cross_rough_terrain_rev";
		public static final String COLUMN_NAME_CROSS_LOW_BAR_FOR = "cross_low_bar_for";
		public static final String COLUMN_NAME_CROSS_LOW_BAR_REV = "cross_low_bar_rev";
		public static final String COLUMN_NAME_SCORE_LOW = "score_low";
		public static final String COLUMN_NAME_SCORE_HIGH = "score_high";
		public static final String COLUMN_NAME_MISS_LOW = "miss_low";
		public static final String COLUMN_NAME_MISS_HIGH = "miss_high";
		public static final String COLUMN_NAME_CHALLENGE = "challenge";
		public static final String COLUMN_NAME_SCALE = "scale";
		public static final String COLUMN_NAME_FOUL = "foul";
		public static final String COLUMN_NAME_YELLOW_CARD = "yellow_card";
		public static final String COLUMN_NAME_RED_CARD = "red_card";
		public static final String COLUMN_NAME_TIP_OVER = "tip_over";
		public static final String COLUMN_NAME_NOTES = "notes";
		public static final String COLUMN_NAME_INVALID = "invalid";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}
	
	public static abstract class NOTES_OPTIONS_Entry implements BaseColumns {
		public static final String TABLE_NAME = "notes_options";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_OPTION_TEXT = "option_text";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class POSITION_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "position_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_POSITION = "position";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class ROBOT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "robot_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_ROBOT_PHOTO = "robot_photo";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class SCOUT_PIT_DATA_2016_Entry implements BaseColumns {
		public static final String TABLE_NAME = "scout_pit_data_2016";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_START_SPY = "start_spy";
		public static final String COLUMN_NAME_AUTO_REACH = "auto_reach";
		public static final String COLUMN_NAME_AUTO_CROSS = "auto_cross";
		public static final String COLUMN_NAME_AUTO_SCORE_LOW = "auto_score_low";
		public static final String COLUMN_NAME_AUTO_SCORE_HIGH = "auto_score_high";
		public static final String COLUMN_NAME_CROSS_PORTCULLIS = "cross_portcullis";
		public static final String COLUMN_NAME_CROSS_CHEVAL = "cross_cheval";
		public static final String COLUMN_NAME_CROSS_MOAT = "cross_moat";
		public static final String COLUMN_NAME_CROSS_RAMPARTS = "cross_ramparts";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_FOR = "cross_drawbridge_for";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_FOR_WITH_HELP = "cross_drawbridge_for_with_help";
		public static final String COLUMN_NAME_CROSS_DRAWBRIDGE_REV = "cross_drawbridge_rev";
		public static final String COLUMN_NAME_CROSS_SALLY_FOR = "cross_sally_for";
		public static final String COLUMN_NAME_CROSS_SALLY_FOR_WITH_HELP = "cross_sally_for_with_help";
		public static final String COLUMN_NAME_CROSS_SALLY_REV = "cross_sally_rev";
		public static final String COLUMN_NAME_CROSS_ROCK_WALL = "cross_rock_wall";
		public static final String COLUMN_NAME_CROSS_ROUGH_TERRAIN = "cross_rough_terrain";
		public static final String COLUMN_NAME_CROSS_LOW_BAR = "cross_low_bar";
		public static final String COLUMN_NAME_SCORE_HIGH = "score_high";
		public static final String COLUMN_NAME_SCORE_LOW = "score_low";
		public static final String COLUMN_NAME_CHALLENGE = "challenge";
		public static final String COLUMN_NAME_SCALE = "scale";
		public static final String COLUMN_NAME_CONFIG_ID = "config_id";
		public static final String COLUMN_NAME_WHEEL_BASE_ID = "wheel_base_id";
		public static final String COLUMN_NAME_WHEEL_TYPE_ID = "wheel_type_id";
		public static final String COLUMN_NAME_NOTES = "notes";
		public static final String COLUMN_NAME_INVALID = "invalid";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}
	
	public static abstract class WHEEL_BASE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_base_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_BASE_DESC = "wheel_base_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class WHEEL_TYPE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_type_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_TYPE_DESC = "wheel_type_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}

	public static final String[] SQL_CREATE_ENTRIES = {
		"CREATE TABLE IF NOT EXISTS configuration_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	configuration_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO configuration_lu\n" +
		"SELECT 1 AS id, 'Wide' AS configuration_desc, '2014-01-25 15:18:38' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Long', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 3, 'Square', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 4, 'Round', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 5, 'Hex', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 6, 'Triangle', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 7, 'Other', '2014-01-25 15:18:38', 0;",
	
		"CREATE TABLE IF NOT EXISTS defense_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	defense_desc text NOT NULL,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n" +
		");",
	
		"INSERT INTO defense_lu\n" +
		"SELECT 1 AS id, 'Portcullis' AS defense_desc, 0 AS invalid, '2016-01-16 18:48:49' AS timestamp\n" +
		"UNION SELECT 2, 'Cheval de frise', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 3, 'Moat', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 4, 'Ramparts', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 5, 'Drawbridge', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 6, 'Sally port', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 7, 'Rock wall', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 8, 'Rough Terrain', 0, '2016-01-16 18:48:49'\n" +
		"UNION SELECT 9, 'Low bar', 0, '2016-01-16 18:48:49';",
	
		"CREATE TABLE IF NOT EXISTS event_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	event_name text NOT NULL,\n" +
		"	event_code text NOT NULL,\n" +
		"	date_start datetime NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO event_lu\n" +
		"SELECT 1 AS id, 'Western Canada Regional' AS event_name, 'ABCA' AS event_code, '2016-04-03 00:00:00' AS date_start, '2016-01-15 01:37:21' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Rocket City Regional', 'ALHU', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 3, 'Arkansas Rock City Regional', 'ARLR', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 4, 'Australia Regional', 'AUSY', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 5, 'Arizona North Regional', 'AZFL', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 6, 'Arizona West Regional', 'AZPX', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 7, 'Sacramento Regional', 'CADA', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 8, 'Los Angeles Regional sponsored by The Roddenberry Foundation', 'CALB', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 9, 'Central Valley Regional', 'CAMA', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 10, 'Orange County Regional', 'CAPL', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 11, 'San Diego Regional', 'CASD', '2016-03-02 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 12, 'Silicon Valley Regional presented by Google.org', 'CASJ', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 13, 'Ventura Regional', 'CAVE', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 14, 'FIRST Chesapeake District Championship', 'CHCMP', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 15, 'FIRST Championship', 'CMP', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 16, 'FIRST Championship - Archimedes Subdivision', 'CMP-ARCHIMEDES', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 17, 'FIRST Championship - ARTE Division', 'CMP-ARTE', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 18, 'FIRST Championship - Carson Subdivision', 'CMP-CARSON', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 19, 'FIRST Championship - Carver Subdivision', 'CMP-CARVER', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 20, 'FIRST Championship - CUCA Division', 'CMP-CUCA', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 21, 'FIRST Championship - Curie Subdivision', 'CMP-CURIE', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 22, 'FIRST Championship - GACA Division', 'CMP-GACA', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 23, 'FIRST Championship - Galileo Subdivision', 'CMP-GALILEO', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 24, 'FIRST Championship - Hopper Subdivision', 'CMP-HOPPER', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 25, 'FIRST Championship - NEHO Division', 'CMP-NEHO', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 26, 'FIRST Championship - Newton Subdivision', 'CMP-NEWTON', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 27, 'FIRST Championship - Tesla Subdivision', 'CMP-TESLA', '2016-04-27 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 28, 'Colorado Regional', 'CODE', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 29, 'NE District - Hartford Event', 'CTHAR', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 30, 'NE District - Waterbury Event', 'CTWAT', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 31, 'Orlando Regional', 'FLOR', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 32, 'South Florida Regional', 'FLWP', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 33, 'PCH District - Albany Event', 'GAALB', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 34, 'Peachtree District State Championship', 'GACMP', '2016-04-14 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 35, 'PCH District - Columbus Event', 'GACOL', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 36, 'PCH District - Dalton Event', 'GADAL', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 37, 'PCH District - Kennesaw Event', 'GAKEN', '2016-04-08 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 38, 'Hawaii Regional', 'HIHO', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 39, 'Iowa Regional', 'IACF', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 40, 'Idaho Regional', 'IDBO', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 41, 'Midwest Regional', 'ILCH', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 42, 'Central Illinois Regional', 'ILPE', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 43, 'Indiana State Championship', 'INCMP', '2016-04-13 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 44, 'IN District - Perry Meridian Event', 'INPMH', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 45, 'IN District - Walker Warren Event', 'INWCH', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 46, 'IN District - Tippecanoe Event', 'INWLA', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 47, 'Israel Regional', 'ISTA', '2016-03-08 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 48, 'Bayou Regional', 'LAKE', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 49, 'NE District - Boston Event', 'MABOS', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 50, 'NE District - UMass-Dartmouth Event', 'MANDA', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 51, 'NE District - North Shore Event', 'MAREA', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 52, 'NE District - WPI Event', 'MAWOR', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 53, 'CHS District - Greater DC Event', 'MDBET', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 54, 'CHS District - Northern Maryland Event', 'MDBLR', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 55, 'CHS District - Central Maryland Event', 'MDEDG', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 56, 'NE District - Pine Tree Event', 'MELEW', '2016-04-07 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 57, 'FIM District - Ann Arbor Skyline Event', 'MIANN', '2016-04-07 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 58, 'FIM District - Woodhaven Event', 'MIBRO', '2016-04-07 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 59, 'FIM District - Center Line Event', 'MICEN', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 60, 'Michigan State Championship', 'MICMP', '2016-04-13 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 61, 'FIM District - Escanaba Event', 'MIESC', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 62, 'FIM District - Howell Event', 'MIHOW', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 63, 'FIM District - Kettering University Event #2', 'MIKE2', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 64, 'FIM District - East Kentwood Event', 'MIKEN', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 65, 'FIM District - Kettering University Event #1', 'MIKET', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 66, 'FIM District - Lakeview Event', 'MILAK', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 67, 'FIM District - Lansing Event', 'MILAN', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 68, 'FIM District - Livonia Event', 'MILIV', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 69, 'FIM District - Lake Superior State University Event', 'MILSU', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 70, 'FIM District - Marysville Event', 'MIMAR', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 71, 'FIM District - Midland Event', 'MIMID', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 72, 'FIM District - St. Joseph Event', 'MISJO', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 73, 'FIM District - Southfield Event', 'MISOU', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 74, 'FIM District - Standish-Sterling Event', 'MISTA', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 75, 'FIM District - Troy Event', 'MITRY', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 76, 'FIM District - Traverse City Event', 'MITVC', '2016-04-07 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 77, 'FIM District - Waterford Event', 'MIWAT', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 78, 'FIM District - West Michigan Event', 'MIWMI', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 79, 'Lake Superior Regional', 'MNDU', '2016-03-02 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 80, 'Northern Lights Regional', 'MNDU2', '2016-03-02 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 81, 'Minnesota 10000 Lakes Regional', 'MNMI', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 82, 'Minnesota North Star Regional', 'MNMI2', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 83, 'Greater Kansas City Regional', 'MOKC', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 84, 'St. Louis Regional', 'MOSL', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 85, 'Mid-Atlantic Robotics District Championship', 'MRCMP', '2016-04-13 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 86, 'Mexico City Regional', 'MXMC', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 87, 'NC District - UNC Asheville Event', 'NCASH', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 88, 'NC District - Campbell University/Johnston Community College Event', 'NCBUI', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 89, 'NC FIRST Robotics State Championship', 'NCCMP', '2016-04-08 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 90, 'NC District - Guilford County Event', 'NCMCL', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 91, 'NC District - Wake County Event', 'NCRAL', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 92, 'New England District Championship', 'NECMP', '2016-04-13 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 93, 'NE District - UNH Event', 'NHDUR', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 94, 'NE District - Granite State Event', 'NHGRS', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 95, 'MAR District - Bridgewater-Raritan Event', 'NJBRI', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 96, 'MAR District - Mt. Olive Event', 'NJFLA', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 97, 'MAR District - Montgomery Event', 'NJSKI', '2016-04-08 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 98, 'MAR District - Seneca Event', 'NJTAB', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 99, 'Las Vegas Regional', 'NVLV', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 100, 'SBPLI Long Island Regional', 'NYLI', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 101, 'New York City Regional', 'NYNY', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 102, 'Finger Lakes Regional', 'NYRO', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 103, 'New York Tech Valley Regional', 'NYTR', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 104, 'Queen City Regional', 'OHCI', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 105, 'Buckeye Regional', 'OHCL', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 106, 'Oklahoma Regional', 'OKOK', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 107, 'North Bay Regional', 'ONNB', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 108, 'Greater Toronto East Regional', 'ONTO', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 109, 'Greater Toronto Central Regional', 'ONTO2', '2016-03-02 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 110, 'Waterloo Regional', 'ONWA', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 111, 'Windsor Essex Great Lakes Regional', 'ONWI', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 112, 'PNW District - Clackamas Academy of Industrial Science Event', 'ORORE', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 113, 'PNW District - Philomath Event', 'ORPHI', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 114, 'PNW District - Wilsonville Event', 'ORWIL', '2016-03-10 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 115, 'Greater Pittsburgh Regional', 'PACA', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 116, 'MAR District - Hatboro-Horsham Event', 'PAHAT', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 117, 'MAR District - Springside Chestnut Hill Event', 'PAPHI', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 118, 'MAR District - Westtown Event', 'PAWCH', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 119, 'Pacific Northwest District Championship sponsored by Autodesk', 'PNCMP', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 120, 'FRC Festival de Robotique - Montreal Regional', 'QCMO', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 121, 'NE District - Rhode Island Event', 'RIPRO', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 122, 'Palmetto Regional', 'SCMB', '2016-02-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 123, 'Smoky Mountains Regional', 'TNKN', '2016-03-30 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 124, 'Dallas Regional', 'TXDA', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 125, 'Lone Star Regional', 'TXHO', '2016-04-06 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 126, 'Hub City Regional', 'TXLU', '2016-03-31 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 127, 'Alamo Regional sponsored by Rackspace Hosting', 'TXSA', '2016-03-09 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 128, 'Utah Regional', 'UTWV', '2016-03-16 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 129, 'CHS District - Southwest Virginia Event', 'VABLA', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 130, 'CHS District - Central Virginia Event', 'VADOS', '2016-03-24 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 131, 'CHS District - Northern Virginia Event', 'VAHAY', '2016-03-04 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 132, 'CHS District - Hampton Roads Event', 'VAPOR', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 133, 'PNW District - Auburn Event', 'WAAHS', '2016-04-01 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 134, 'PNW District - Auburn Mountainview Event', 'WAAMV', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 135, 'PNW District - Central Washington University Event', 'WAELL', '2016-03-17 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 136, 'PNW District - Mount Vernon Event', 'WAMOU', '2016-03-18 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 137, 'PNW District - Glacier Peak Event', 'WASNO', '2016-03-11 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 138, 'PNW District - West Valley Event', 'WASPO', '2016-03-03 00:00:00', '2016-01-15 01:37:21', 0\n" +
		"UNION SELECT 139, 'Wisconsin Regional', 'WIMI', '2016-03-23 00:00:00', '2016-01-15 01:37:21', 0;",
	
		"CREATE TABLE IF NOT EXISTS fact_match_data_2016 (\n" +
		"	id integer primary key autoincrement,\n" +
		"	event_id unsigned int(4) NOT NULL,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	match_id unsigned int(4) NOT NULL,\n" +
		"	practice_match tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	position_id unsigned int(3) NOT NULL,\n" +
		"	red_def_2 unsigned int(2) NOT NULL,\n" +
		"	red_def_3 unsigned int(2) NOT NULL,\n" +
		"	red_def_4 unsigned int(2) NOT NULL,\n" +
		"	red_def_5 unsigned int(2) NOT NULL,\n" +
		"	blue_def_2 unsigned int(2) NOT NULL,\n" +
		"	blue_def_3 unsigned int(2) NOT NULL,\n" +
		"	blue_def_4 unsigned int(2) NOT NULL,\n" +
		"	blue_def_5 unsigned int(2) NOT NULL,\n" +
		"	auto_reach tinyint(1) NOT NULL,\n" +
		"	start_spy tinyint(1) NOT NULL,\n" +
		"	auto_cross_portcullis_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_portcullis_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_cheval_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_cheval_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_moat_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_moat_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_ramparts_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_ramparts_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_drawbridge_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_drawbridge_for_with_help unsigned int(3) NOT NULL,\n" +
		"	auto_cross_drawbridge_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_sally_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_sally_for_with_help unsigned int(3) NOT NULL,\n" +
		"	auto_cross_sally_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_rock_wall_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_rock_wall_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_rough_terrain_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_rough_terrain_rev unsigned int(3) NOT NULL,\n" +
		"	auto_cross_low_bar_for unsigned int(3) NOT NULL,\n" +
		"	auto_cross_low_bar_rev unsigned int(3) NOT NULL,\n" +
		"	auto_score_low unsigned int(3) NOT NULL,\n" +
		"	auto_score_high unsigned int(3) NOT NULL,\n" +
		"	auto_miss_low unsigned int(3) NOT NULL,\n" +
		"	auto_miss_high unsigned int(3) NOT NULL,\n" +
		"	cross_portcullis_for unsigned int(3) NOT NULL,\n" +
		"	cross_portcullis_rev unsigned int(3) NOT NULL,\n" +
		"	cross_cheval_for unsigned int(3) NOT NULL,\n" +
		"	cross_cheval_rev unsigned int(3) NOT NULL,\n" +
		"	cross_moat_for unsigned int(3) NOT NULL,\n" +
		"	cross_moat_rev unsigned int(3) NOT NULL,\n" +
		"	cross_ramparts_for unsigned int(3) NOT NULL,\n" +
		"	cross_ramparts_rev unsigned int(3) NOT NULL,\n" +
		"	cross_drawbridge_for unsigned int(3) NOT NULL,\n" +
		"	cross_drawbridge_for_with_help unsigned int(3) NOT NULL,\n" +
		"	cross_drawbridge_rev unsigned int(3) NOT NULL,\n" +
		"	cross_sally_for unsigned int(3) NOT NULL,\n" +
		"	cross_sally_for_with_help unsigned int(3) NOT NULL,\n" +
		"	cross_sally_rev unsigned int(3) NOT NULL,\n" +
		"	cross_rock_wall_for unsigned int(3) NOT NULL,\n" +
		"	cross_rock_wall_rev unsigned int(3) NOT NULL,\n" +
		"	cross_rough_terrain_for unsigned int(3) NOT NULL,\n" +
		"	cross_rough_terrain_rev unsigned int(3) NOT NULL,\n" +
		"	cross_low_bar_for unsigned int(3) NOT NULL,\n" +
		"	cross_low_bar_rev unsigned int(3) NOT NULL,\n" +
		"	score_low unsigned int(3) NOT NULL,\n" +
		"	score_high unsigned int(3) NOT NULL,\n" +
		"	miss_low unsigned int(3) NOT NULL,\n" +
		"	miss_high unsigned int(3) NOT NULL,\n" +
		"	challenge tinyint(1) NOT NULL,\n" +
		"	scale tinyint(1) NOT NULL,\n" +
		"	foul tinyint(1) NOT NULL,\n" +
		"	yellow_card tinyint(1) NOT NULL,\n" +
		"	red_card tinyint(1) NOT NULL,\n" +
		"	tip_over tinyint(1) NOT NULL,\n" +
		"	notes text NOT NULL,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS notes_options (\n" +
		"	id integer primary key autoincrement,\n" +
		"	option_text text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO notes_options\n" +
		"SELECT 1 AS id, 'No Show' AS option_text, '2014-01-25 15:21:36' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Non-functional', '2014-01-25 15:21:36', 0\n" +
		"UNION SELECT 3, 'Defender', '2016-01-15 16:30:02', 0;",
	
		"CREATE TABLE IF NOT EXISTS position_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	position text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO position_lu\n" +
		"SELECT 1 AS id, 'Red 1' AS position, '2015-02-12 00:30:10' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Red 2', '2015-02-12 00:30:10', 0\n" +
		"UNION SELECT 3, 'Red 3', '2015-02-12 00:30:36', 0\n" +
		"UNION SELECT 4, 'Blue 1', '2015-02-12 00:30:36', 0\n" +
		"UNION SELECT 5, 'Blue 2', '2015-02-12 00:30:50', 0\n" +
		"UNION SELECT 6, 'Blue 3', '2015-02-12 00:30:50', 0;",
	
		"CREATE TABLE IF NOT EXISTS robot_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	robot_photo text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS scout_pit_data_2016 (\n" +
		"	id integer primary key autoincrement,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	start_spy tinyint(1) NOT NULL,\n" +
		"	auto_reach tinyint(1) NOT NULL,\n" +
		"	auto_cross tinyint(1) NOT NULL,\n" +
		"	auto_score_low unsigned int(2) NOT NULL,\n" +
		"	auto_score_high unsigned int(2) NOT NULL,\n" +
		"	cross_portcullis tinyint(1) NOT NULL,\n" +
		"	cross_cheval tinyint(1) NOT NULL,\n" +
		"	cross_moat tinyint(1) NOT NULL,\n" +
		"	cross_ramparts tinyint(1) NOT NULL,\n" +
		"	cross_drawbridge_for tinyint(1) NOT NULL,\n" +
		"	cross_drawbridge_for_with_help tinyint(1) NOT NULL,\n" +
		"	cross_drawbridge_rev tinyint(1) NOT NULL,\n" +
		"	cross_sally_for tinyint(1) NOT NULL,\n" +
		"	cross_sally_for_with_help tinyint(1) NOT NULL,\n" +
		"	cross_sally_rev tinyint(1) NOT NULL,\n" +
		"	cross_rock_wall tinyint(1) NOT NULL,\n" +
		"	cross_rough_terrain tinyint(1) NOT NULL,\n" +
		"	cross_low_bar tinyint(1) NOT NULL,\n" +
		"	score_high tinyint(1) NOT NULL,\n" +
		"	score_low tinyint(1) NOT NULL,\n" +
		"	challenge tinyint(1) NOT NULL,\n" +
		"	scale tinyint(1) NOT NULL,\n" +
		"	config_id unsigned int(3) NOT NULL,\n" +
		"	wheel_base_id unsigned int(3) NOT NULL,\n" +
		"	wheel_type_id unsigned int(3) NOT NULL,\n" +
		"	notes text NOT NULL,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS wheel_base_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	wheel_base_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO wheel_base_lu\n" +
		"SELECT 1 AS id, '2 Wheel Drive' AS wheel_base_desc, '2014-01-25 15:23:47' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, '4 Wheel Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 3, '6 Wheel Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 5, 'Crab Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 6, 'Swerve Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 7, 'Tank Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 8, 'Other', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 4, '8 Wheel Drive (or more)', '2014-01-25 15:23:47', 0;",
	
		"CREATE TABLE IF NOT EXISTS wheel_type_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	wheel_type_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO wheel_type_lu\n" +
		"SELECT 1 AS id, 'Kit Wheels' AS wheel_type_desc, '2014-01-25 15:25:39' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'IFI', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 3, 'Omni', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 4, 'Mecanum', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 5, 'Nylon', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 6, 'Rubber', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 7, 'Tank Tread', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 8, 'Swerve', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 9, 'Custom', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 10, 'Pneumatic', '2014-01-25 15:25:39', 0;"
	};

	public static final String[] SQL_DELETE_ENTRIES = {
		"DROP TABLE IF EXISTS configuration_lu;",
		"DROP TABLE IF EXISTS defense_lu;",
		"DROP TABLE IF EXISTS event_lu;",
		"DROP TABLE IF EXISTS fact_match_data_2016;",
		"DROP TABLE IF EXISTS notes_options;",
		"DROP TABLE IF EXISTS position_lu;",
		"DROP TABLE IF EXISTS robot_lu;",
		"DROP TABLE IF EXISTS scout_pit_data_2016;",
		"DROP TABLE IF EXISTS wheel_base_lu;",
		"DROP TABLE IF EXISTS wheel_type_lu;"
	};

}