/*
-----------------------------------------------------
SQLITEContractGen.py 2.0

This file was autogenerated with run cmd:
  "SQLITEContractGen.py --packagename=org.frc836.database --classname=FRCScoutingContract --infile=FRC_Scouting_Server/scouting.sql --outfile=src/org/frc836/database/FRCScoutingContract.java"

python version info:
  2.7.3 (default, Dec 18 2014, 19:10:20) 
[GCC 4.6.3]

Please take heed of modifying unnecessarily
-----------------------------------------------------
*/

package org.frc836.database;

import android.provider.BaseColumns;

public final class FRCScoutingContract {
	public FRCScoutingContract() {};

	public static abstract class CONFIGURATION_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "configuration_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_CONFIGURATION_DESC = "configuration_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class EVENT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "event_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_NAME = "event_name";
		public static final String COLUMN_NAME_EVENT_CODE = "event_code";
		public static final String COLUMN_NAME_DATE_START = "date_start";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class FACT_MATCH_DATA_2015_Entry implements BaseColumns {
		public static final String TABLE_NAME = "fact_match_data_2015";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_ID = "event_id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_MATCH_ID = "match_id";
		public static final String COLUMN_NAME_PRACTICE_MATCH = "practice_match";
		public static final String COLUMN_NAME_POSITION_ID = "position_id";
		public static final String COLUMN_NAME_AUTO_MOVE = "auto_move";
		public static final String COLUMN_NAME_AUTO_TOTES = "auto_totes";
		public static final String COLUMN_NAME_AUTO_STACK_2 = "auto_stack_2";
		public static final String COLUMN_NAME_AUTO_STACK_3 = "auto_stack_3";
		public static final String COLUMN_NAME_AUTO_BIN = "auto_bin";
		public static final String COLUMN_NAME_AUTO_STEP_BIN = "auto_step_bin";
		public static final String COLUMN_NAME_TOTES_1 = "totes_1";
		public static final String COLUMN_NAME_TOTES_2 = "totes_2";
		public static final String COLUMN_NAME_TOTES_3 = "totes_3";
		public static final String COLUMN_NAME_TOTES_4 = "totes_4";
		public static final String COLUMN_NAME_TOTES_5 = "totes_5";
		public static final String COLUMN_NAME_TOTES_6 = "totes_6";
		public static final String COLUMN_NAME_COOP_1 = "coop_1";
		public static final String COLUMN_NAME_COOP_2 = "coop_2";
		public static final String COLUMN_NAME_COOP_3 = "coop_3";
		public static final String COLUMN_NAME_COOP_4 = "coop_4";
		public static final String COLUMN_NAME_BIN_1 = "bin_1";
		public static final String COLUMN_NAME_BIN_2 = "bin_2";
		public static final String COLUMN_NAME_BIN_3 = "bin_3";
		public static final String COLUMN_NAME_BIN_4 = "bin_4";
		public static final String COLUMN_NAME_BIN_5 = "bin_5";
		public static final String COLUMN_NAME_BIN_6 = "bin_6";
		public static final String COLUMN_NAME_BIN_LITTER = "bin_litter";
		public static final String COLUMN_NAME_LANDFILL_LITTER = "landfill_litter";
		public static final String COLUMN_NAME_TIPPED_STACK = "tipped_stack";
		public static final String COLUMN_NAME_FOUL = "foul";
		public static final String COLUMN_NAME_YELLOW_CARD = "yellow_card";
		public static final String COLUMN_NAME_RED_CARD = "red_card";
		public static final String COLUMN_NAME_TIP_OVER = "tip_over";
		public static final String COLUMN_NAME_NOTES = "notes";
		public static final String COLUMN_NAME_INVALID = "invalid";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}
	
	public static abstract class NOTES_OPTIONS_Entry implements BaseColumns {
		public static final String TABLE_NAME = "notes_options";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_OPTION_TEXT = "option_text";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class POSITION_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "position_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_POSITION = "position";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class ROBOT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "robot_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_ROBOT_PHOTO = "robot_photo";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class SCOUT_PIT_DATA_2015_Entry implements BaseColumns {
		public static final String TABLE_NAME = "scout_pit_data_2015";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_PUSH_TOTE = "push_tote";
		public static final String COLUMN_NAME_PUSH_BIN = "push_bin";
		public static final String COLUMN_NAME_LIFT_TOTE = "lift_tote";
		public static final String COLUMN_NAME_LIFT_BIN = "lift_bin";
		public static final String COLUMN_NAME_PUSH_LITTER = "push_litter";
		public static final String COLUMN_NAME_LOAD_LITTER = "load_litter";
		public static final String COLUMN_NAME_STACK_TOTE_HEIGHT = "stack_tote_height";
		public static final String COLUMN_NAME_STACK_BIN_HEIGHT = "stack_bin_height";
		public static final String COLUMN_NAME_COOP_TOTES = "coop_totes";
		public static final String COLUMN_NAME_COOP_STACK_HEIGHT = "coop_stack_height";
		public static final String COLUMN_NAME_MOVE_AUTO = "move_auto";
		public static final String COLUMN_NAME_AUTO_BIN_SCORE = "auto_bin_score";
		public static final String COLUMN_NAME_AUTO_TOTE_SCORE = "auto_tote_score";
		public static final String COLUMN_NAME_AUTO_TOTE_STACK_HEIGHT = "auto_tote_stack_height";
		public static final String COLUMN_NAME_AUTO_STEP_BINS = "auto_step_bins";
		public static final String COLUMN_NAME_CONFIG_ID = "config_id";
		public static final String COLUMN_NAME_WHEEL_BASE_ID = "wheel_base_id";
		public static final String COLUMN_NAME_WHEEL_TYPE_ID = "wheel_type_id";
		public static final String COLUMN_NAME_MANIP_STYLE = "manip_style";
		public static final String COLUMN_NAME_NEED_UPRIGHT_TOTE = "need_upright_tote";
		public static final String COLUMN_NAME_NEED_UPRIGHT_BIN = "need_upright_bin";
		public static final String COLUMN_NAME_CAN_UPRIGHT_TOTE = "can_upright_tote";
		public static final String COLUMN_NAME_CAN_UPRIGHT_BIN = "can_upright_bin";
		public static final String COLUMN_NAME_NOTES = "notes";
		public static final String COLUMN_NAME_INVALID = "invalid";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}
	
	public static abstract class WHEEL_BASE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_base_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_BASE_DESC = "wheel_base_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}
	
	public static abstract class WHEEL_TYPE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_type_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_TYPE_DESC = "wheel_type_desc";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
		public static final String COLUMN_NAME_INVALID = "invalid";
	}

	public static final String[] SQL_CREATE_ENTRIES = {
		"CREATE TABLE IF NOT EXISTS configuration_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	configuration_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO configuration_lu\n" +
		"SELECT 1 AS id, 'Wide' AS configuration_desc, '2014-01-25 15:18:38' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Long', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 3, 'Square', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 4, 'Round', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 5, 'Hex', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 6, 'Triangle', '2014-01-25 15:18:38', 0\n" +
		"UNION SELECT 7, 'Other', '2014-01-25 15:18:38', 0;",
	
		"CREATE TABLE IF NOT EXISTS event_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	event_name text NOT NULL,\n" +
		"	event_code text NOT NULL,\n" +
		"	date_start datetime NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO event_lu\n" +
		"SELECT 1 AS id, 'Western Canada Regional' AS event_name, 'ABCA' AS event_code, '2015-04-01 00:00:00' AS date_start, '2015-02-21 17:18:53' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Arkansas Rock City Regional', 'ARFA', '2015-03-04 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 3, 'Australia Regional', 'AUSY', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 4, 'Arizona East Regional', 'AZCH', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 5, 'Arizona West Regional', 'AZPX', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 6, 'Los Angeles Regional sponsored by The Roddenberry Foundation', 'CALB', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 7, 'Central Valley Regional', 'CAMA', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 8, 'Inland Empire Regional', 'CARM', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 9, 'Sacramento Regional', 'CASA', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 10, 'San Diego Regional', 'CASD', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 11, 'Silicon Valley Regional', 'CASJ', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 12, 'Ventura Regional', 'CAVE', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 13, 'FIRST Championship', 'CMP', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 14, 'FIRST Championship - Archimedes Subdivision', 'CMP-ARCHIMEDES', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 15, 'FIRST Championship - ARTE Division', 'CMP-ARTE', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 16, 'FIRST Championship - Carson Subdivision', 'CMP-CARSON', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 17, 'FIRST Championship - Carver Subdivision', 'CMP-CARVER', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 18, 'FIRST Championship - CUCA Division', 'CMP-CUCA', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 19, 'FIRST Championship - Curie Subdivision', 'CMP-CURIE', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 20, 'FIRST Championship - GACA Division', 'CMP-GACA', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 21, 'FIRST Championship - Galileo Subdivision', 'CMP-GALILEO', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 22, 'FIRST Championship - Hopper Subdivision', 'CMP-HOPPER', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 23, 'FIRST Championship - NEHO Division', 'CMP-NEHO', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 24, 'FIRST Championship - Newton Subdivision', 'CMP-NEWTON', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 25, 'FIRST Championship - Tesla Subdivision', 'CMP-TESLA', '2015-04-22 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 26, 'Colorado Regional', 'CODE', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 27, 'NE District - Hartford Event', 'CTHAR', '2015-03-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 28, 'NE District - Waterbury Event', 'CTWAT', '2015-02-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 29, 'Greater DC Regional', 'DCWA', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 30, 'South Florida Regional', 'FLFO', '2015-02-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 31, 'Orlando Regional', 'FLOR', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 32, 'Peachtree Regional', 'GADU', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 33, 'Georgia Southern Classic Regional', 'GAPE', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 34, 'Hawaii Regional', 'HIHO', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 35, 'Midwest Regional', 'ILCH', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 36, 'Central Illinois Regional', 'ILIL', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 37, 'Indiana FIRST District Championship', 'INCMP', '2015-04-02 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 38, 'IN District - Indianapolis Event', 'ININD', '2015-02-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 39, 'IN District - Kokomo City of Firsts Event sponsored by AndyMark', 'INKOK', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 40, 'IN District - Purdue Event', 'INWLA', '2015-03-19 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 41, 'Israel Regional', 'ISTA', '2015-03-09 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 42, 'Bayou Regional', 'LAKE', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 43, 'NE District - Northeastern University Event', 'MABOS', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 44, 'NE District - UMass - Dartmouth Event', 'MANDA', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 45, 'NE District - Reading Event', 'MAREA', '2015-03-06 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 46, 'NE District - Pioneer Valley Event', 'MASPR', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 47, 'Chesapeake Regional', 'MDCP', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 48, 'NE District - Pine Tree Event', 'MELEW', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 49, 'FIM District - Bedford Event', 'MIBED', '2015-04-02 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 50, 'FIM District - Center Line Event', 'MICEN', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 51, 'FIRST in Michigan District Championship', 'MICMP', '2015-04-08 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 52, 'FIM District - Escanaba Event', 'MIESC', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 53, 'FIM District - Woodhaven Event', 'MIFLA', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 54, 'FIM District - Gull Lake Event', 'MIGUL', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 55, 'FIM District - Howell Event', 'MIHOW', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 56, 'FIM District - Kentwood Event', 'MIKEN', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 57, 'FIM District - Kettering University Event', 'MIKET', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 58, 'FIM District - Lansing Event', 'MILAN', '2015-04-02 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 59, 'FIM District - Livonia Event', 'MILIV', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 60, 'FIM District - Great Lakes Bay Region Event', 'MIMID', '2015-03-19 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 61, 'FIM District - St. Joseph Event', 'MISJO', '2015-03-19 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 62, 'FIM District - Southfield Event', 'MISOU', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 63, 'FIM District - Standish Event', 'MISTA', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 64, 'FIM District - Troy Event', 'MITRY', '2015-04-02 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 65, 'FIM District - Traverse City Event', 'MITVC', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 66, 'FIM District - Waterford Event', 'MIWAT', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 67, 'FIM District - West Michigan Event', 'MIWMI', '2015-03-19 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 68, 'Lake Superior Regional', 'MNDU', '2015-02-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 69, 'Northern Lights Regional', 'MNDU2', '2015-02-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 70, 'Minnesota 10000 Lakes Regional', 'MNMI', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 71, 'Minnesota North Star Regional', 'MNMI2', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 72, 'Greater Kansas City Regional', 'MOKC', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 73, 'St. Louis Regional', 'MOSL', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 74, 'Mid-Atlantic Robotics District Championship', 'MRCMP', '2015-04-08 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 75, 'Mexico City Regional', 'MXMC', '2015-03-04 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 76, 'North Carolina Regional', 'NCRE', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 77, 'NE FIRST District Championship presented by United Technologies', 'NECMP', '2015-04-08 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 78, 'NE District - UNH Event', 'NHDUR', '2015-03-20 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 79, 'NE District - Granite State Event', 'NHNAS', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 80, 'MAR District - Bridgewater-Raritan Event', 'NJBRI', '2015-03-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 81, 'MAR District - Mt. Olive Event', 'NJFLA', '2015-03-06 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 82, 'MAR District - North Brunswick Event', 'NJNBR', '2015-04-02 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 83, 'MAR District - Seneca Event', 'NJTAB', '2015-03-20 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 84, 'Las Vegas Regional', 'NVLV', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 85, 'SBPLI Long Island Regional', 'NYLI', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 86, 'New York City Regional', 'NYNY', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 87, 'Finger Lakes Regional', 'NYRO', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 88, 'New York Tech Valley Regional', 'NYTR', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 89, 'Queen City Regional', 'OHCI', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 90, 'Buckeye Regional', 'OHCL', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 91, 'Oklahoma Regional', 'OKOK', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 92, 'North Bay Regional', 'ONNB', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 93, 'Greater Toronto East Regional', 'ONTO', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 94, 'Greater Toronto Central Regional', 'ONTO2', '2015-03-04 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 95, 'Waterloo Regional', 'ONWA', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 96, 'Windsor Essex Great Lakes Regional', 'ONWI', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 97, 'PNW District - Oregon City Event', 'ORORE', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 98, 'PNW District - Philomath Event', 'ORPHI', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 99, 'PNW District - Wilsonville Event', 'ORWIL', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 100, 'MAR District - Upper Darby Event', 'PADRE', '2015-03-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 101, 'MAR District - Hatboro-Horsham Event', 'PAHAT', '2015-02-27 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 102, 'MAR District - Springside Chestnut Hill Event', 'PAPHI', '2015-03-12 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 103, 'Greater Pittsburgh Regional', 'PAPI', '2015-03-04 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 104, 'Pacific Northwest District Championship', 'PNCMP', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 105, 'FRC Festival de Robotique - Montreal Regional', 'QCMO', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 106, 'NE District - Rhode Island Event', 'RISMI', '2015-03-20 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 107, 'Palmetto Regional', 'SCMB', '2015-02-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 108, 'Smoky Mountains Regional', 'TNKN', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 109, 'Dallas Regional', 'TXDA', '2015-02-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 110, 'Lone Star Regional', 'TXHO', '2015-04-01 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 111, 'Hub City Regional', 'TXLU', '2015-03-25 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 112, 'Alamo Regional sponsored by Rackspace Hosting', 'TXSA', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 113, 'Utah Regional', 'UTWV', '2015-03-11 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 114, 'Virginia Regional', 'VARI', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 115, 'PNW District - Auburn Event', 'WAAHS', '2015-03-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 116, 'PNW District - Auburn Mountainview Event', 'WAAMV', '2015-02-26 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 117, 'PNW District - Central Washington University Event', 'WAELL', '2015-03-19 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 118, 'PNW District - Mount Vernon Event', 'WAMOU', '2015-03-13 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 119, 'PNW District - Shorewood Event', 'WASHO', '2015-03-20 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 120, 'PNW District - Glacier Peak Event', 'WASNO', '2015-03-06 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 121, 'PNW District - West Valley Event', 'WASPO', '2015-03-05 00:00:00', '2015-02-21 17:18:53', 0\n" +
		"UNION SELECT 122, 'Wisconsin Regional', 'WIMI', '2015-03-18 00:00:00', '2015-02-21 17:18:53', 0;",
	
		"CREATE TABLE IF NOT EXISTS fact_match_data_2015 (\n" +
		"	id integer primary key autoincrement,\n" +
		"	event_id unsigned int(4) NOT NULL,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	match_id unsigned int(4) NOT NULL,\n" +
		"	practice_match tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	position_id unsigned int(3) NOT NULL,\n" +
		"	auto_move tinyint(1) NOT NULL,\n" +
		"	auto_totes unsigned int(2) NOT NULL,\n" +
		"	auto_stack_2 tinyint(1) NOT NULL,\n" +
		"	auto_stack_3 tinyint(1) NOT NULL,\n" +
		"	auto_bin unsigned int(2) NOT NULL,\n" +
		"	auto_step_bin unsigned int(2) NOT NULL,\n" +
		"	totes_1 unsigned int(3) NOT NULL,\n" +
		"	totes_2 unsigned int(3) NOT NULL,\n" +
		"	totes_3 unsigned int(3) NOT NULL,\n" +
		"	totes_4 unsigned int(3) NOT NULL,\n" +
		"	totes_5 unsigned int(3) NOT NULL,\n" +
		"	totes_6 unsigned int(3) NOT NULL,\n" +
		"	coop_1 unsigned int(2) NOT NULL,\n" +
		"	coop_2 unsigned int(2) NOT NULL,\n" +
		"	coop_3 unsigned int(2) NOT NULL,\n" +
		"	coop_4 unsigned int(2) NOT NULL,\n" +
		"	bin_1 unsigned int(3) NOT NULL,\n" +
		"	bin_2 unsigned int(3) NOT NULL,\n" +
		"	bin_3 unsigned int(3) NOT NULL,\n" +
		"	bin_4 unsigned int(3) NOT NULL,\n" +
		"	bin_5 unsigned int(3) NOT NULL,\n" +
		"	bin_6 unsigned int(3) NOT NULL,\n" +
		"	bin_litter unsigned int(3) NOT NULL,\n" +
		"	landfill_litter unsigned int(3) NOT NULL,\n" +
		"	tipped_stack tinyint(1) NOT NULL,\n" +
		"	foul tinyint(1) NOT NULL,\n" +
		"	yellow_card tinyint(1) NOT NULL,\n" +
		"	red_card tinyint(1) NOT NULL,\n" +
		"	tip_over tinyint(1) NOT NULL,\n" +
		"	notes text NOT NULL,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0',\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS notes_options (\n" +
		"	id integer primary key autoincrement,\n" +
		"	option_text text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO notes_options\n" +
		"SELECT 1 AS id, 'No Show' AS option_text, '2014-01-25 15:21:36' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Non-functional', '2014-01-25 15:21:36', 0\n" +
		"UNION SELECT 4, 'Turned Bin upright', '2015-01-23 00:43:18', 0\n" +
		"UNION SELECT 3, 'Turned Tote upright', '2015-01-23 00:43:18', 0;",
	
		"CREATE TABLE IF NOT EXISTS position_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	position text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO position_lu\n" +
		"SELECT 1 AS id, 'Red 1' AS position, '2015-02-12 00:30:10' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'Red 2', '2015-02-12 00:30:10', 0\n" +
		"UNION SELECT 3, 'Red 3', '2015-02-12 00:30:36', 0\n" +
		"UNION SELECT 4, 'Blue 1', '2015-02-12 00:30:36', 0\n" +
		"UNION SELECT 5, 'Blue 2', '2015-02-12 00:30:50', 0\n" +
		"UNION SELECT 6, 'Blue 3', '2015-02-12 00:30:50', 0;",
	
		"CREATE TABLE IF NOT EXISTS robot_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	robot_photo text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS scout_pit_data_2015 (\n" +
		"	id integer primary key autoincrement,\n" +
		"	team_id unsigned int(5) NOT NULL,\n" +
		"	push_tote tinyint(1) NOT NULL,\n" +
		"	push_bin tinyint(1) NOT NULL,\n" +
		"	lift_tote tinyint(1) NOT NULL,\n" +
		"	lift_bin tinyint(1) NOT NULL,\n" +
		"	push_litter tinyint(1) NOT NULL,\n" +
		"	load_litter tinyint(1) NOT NULL,\n" +
		"	stack_tote_height unsigned int(2) NOT NULL,\n" +
		"	stack_bin_height unsigned int(2) NOT NULL,\n" +
		"	coop_totes unsigned tinyint(1) NOT NULL,\n" +
		"	coop_stack_height unsigned int(2) NOT NULL,\n" +
		"	move_auto tinyint(1) NOT NULL,\n" +
		"	auto_bin_score unsigned int(2) NOT NULL,\n" +
		"	auto_tote_score unsigned int(2) NOT NULL,\n" +
		"	auto_tote_stack_height unsigned int(2) NOT NULL,\n" +
		"	auto_step_bins unsigned int(2) NOT NULL,\n" +
		"	config_id unsigned int(3) NOT NULL,\n" +
		"	wheel_base_id unsigned int(3) NOT NULL,\n" +
		"	wheel_type_id unsigned int(3) NOT NULL,\n" +
		"	manip_style text NOT NULL,\n" +
		"	need_upright_tote tinyint(1) NOT NULL,\n" +
		"	need_upright_bin tinyint(1) NOT NULL,\n" +
		"	can_upright_tote tinyint(1) NOT NULL,\n" +
		"	can_upright_bin tinyint(1) NOT NULL,\n" +
		"	notes text NOT NULL,\n" +
		"	invalid tinyint(1) NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n" +
		");",
	
		"CREATE TABLE IF NOT EXISTS wheel_base_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	wheel_base_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO wheel_base_lu\n" +
		"SELECT 1 AS id, '2 Wheel Drive' AS wheel_base_desc, '2014-01-25 15:23:47' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, '4 Wheel Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 3, '6 Wheel Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 5, 'Crab Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 6, 'Swerve Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 7, 'Tank Drive', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 8, 'Other', '2014-01-25 15:23:47', 0\n" +
		"UNION SELECT 4, '8 Wheel Drive (or more)', '2014-01-25 15:23:47', 0;",
	
		"CREATE TABLE IF NOT EXISTS wheel_type_lu (\n" +
		"	id integer primary key autoincrement,\n" +
		"	wheel_type_desc text NOT NULL,\n" +
		"	timestamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
		"	invalid unsigned tinyint(1) NOT NULL DEFAULT '0'\n" +
		");",
	
		"INSERT INTO wheel_type_lu\n" +
		"SELECT 1 AS id, 'Kit Wheels' AS wheel_type_desc, '2014-01-25 15:25:39' AS timestamp, 0 AS invalid\n" +
		"UNION SELECT 2, 'IFI', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 3, 'Omni', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 4, 'Mecanum', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 5, 'Nylon', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 6, 'Rubber', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 7, 'Tank Tread', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 8, 'Swerve', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 9, 'Custom', '2014-01-25 15:25:39', 0\n" +
		"UNION SELECT 10, 'Pneumatic', '2014-01-25 15:25:39', 0;"
	};

	public static final String[] SQL_DELETE_ENTRIES = {
		"DROP TABLE IF EXISTS configuration_lu;",
		"DROP TABLE IF EXISTS event_lu;",
		"DROP TABLE IF EXISTS fact_match_data_2015;",
		"DROP TABLE IF EXISTS notes_options;",
		"DROP TABLE IF EXISTS position_lu;",
		"DROP TABLE IF EXISTS robot_lu;",
		"DROP TABLE IF EXISTS scout_pit_data_2015;",
		"DROP TABLE IF EXISTS wheel_base_lu;",
		"DROP TABLE IF EXISTS wheel_type_lu;"
	};

}