package org.frc836.database;

import android.provider.BaseColumns;

/* This file was auto-generated by SQLITEContractGen.py.
 Abandon all hope ye who edit here.*/

final class FRCScoutingContract {

	public FRCScoutingContract() {};

	public static abstract class CONFIGURATION_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "configuration_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_CONFIGURATION_DESC = "configuration_desc";
	}

	public static abstract class EVENT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "event_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_NAME = "event_name";
		public static final String COLUMN_NAME_MATCH_URL = "match_url";
	}

	public static abstract class FACT_MATCH_DATA_Entry implements BaseColumns {
		public static final String TABLE_NAME = "fact_match_data";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_EVENT_ID = "event_id";
		public static final String COLUMN_NAME_MATCH_ID = "match_id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_AUTO_SCORE_HIGH = "auto_score_high";
		public static final String COLUMN_NAME_AUTO_SCORE_HIGH_ATTEMPT = "auto_score_high_attempt";
		public static final String COLUMN_NAME_AUTO_SCORE_MID_LEFT = "auto_score_mid_left";
		public static final String COLUMN_NAME_AUTO_SCORE_MID_LEFT_ATTEMPT = "auto_score_mid_left_attempt";
		public static final String COLUMN_NAME_AUTO_SCORE_MID_RIGHT = "auto_score_mid_right";
		public static final String COLUMN_NAME_AUTO_SCORE_MID_RIGHT_ATTEMPT = "auto_score_mid_right_attempt";
		public static final String COLUMN_NAME_AUTO_SCORE_LOW = "auto_score_low";
		public static final String COLUMN_NAME_AUTO_SCORE_LOW_ATTEMPT = "auto_score_low_attempt";
		public static final String COLUMN_NAME_SCORE_HIGH = "score_high";
		public static final String COLUMN_NAME_SCORE_HIGH_ATTEMPT = "score_high_attempt";
		public static final String COLUMN_NAME_SCORE_MID_LEFT = "score_mid_left";
		public static final String COLUMN_NAME_SCORE_MID_LEFT_ATTEMPT = "score_mid_left_attempt";
		public static final String COLUMN_NAME_SCORE_MID_RIGHT = "score_mid_right";
		public static final String COLUMN_NAME_SCORE_MID_RIGHT_ATTEMPT = "score_mid_right_attempt";
		public static final String COLUMN_NAME_SCORE_LOW = "score_low";
		public static final String COLUMN_NAME_SCORE_LOW_ATTEMPT = "score_low_attempt";
		public static final String COLUMN_NAME_SCORE_PYRAMID = "score_pyramid";
		public static final String COLUMN_NAME_SCORE_PYRAMID_ATTEMPT = "score_pyramid_attempt";
		public static final String COLUMN_NAME_PYRAMID_LEVEL_CLIMBED = "pyramid_level_climbed";
		public static final String COLUMN_NAME_PYRAMID_ATTEMPTED = "pyramid_attempted";
		public static final String COLUMN_NAME_PENALTY = "penalty";
		public static final String COLUMN_NAME_MPENALTY = "mpenalty";
		public static final String COLUMN_NAME_TIP_OVER = "tip_over";
		public static final String COLUMN_NAME_YELLOW_CARD = "yellow_card";
		public static final String COLUMN_NAME_RED_CARD = "red_card";
		public static final String COLUMN_NAME_NOTES = "notes";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}

	public static abstract class NOTES_OPTIONS_Entry implements BaseColumns {
		public static final String TABLE_NAME = "notes_options";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_OPTION_TEXT = "option_text";
	}

	public static abstract class ROBOT_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "robot_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_ROBOT_PHOTO = "robot_photo";
	}

	public static abstract class SCOUT_PIT_DATA_Entry implements BaseColumns {
		public static final String TABLE_NAME = "scout_pit_data";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_TEAM_ID = "team_id";
		public static final String COLUMN_NAME_CONFIGURATION_ID = "configuration_id";
		public static final String COLUMN_NAME_WHEEL_TYPE_ID = "wheel_type_id";
		public static final String COLUMN_NAME_WHEEL_BASE_ID = "wheel_base_id";
		public static final String COLUMN_NAME_AUTONOMOUS_MODE = "autonomous_mode";
		public static final String COLUMN_NAME_SCOUT_COMMENTS = "scout_comments";
		public static final String COLUMN_NAME_PYRAMID_CLIMB_LEVEL = "pyramid_climb_level";
		public static final String COLUMN_NAME_SCORE_HIGH = "score_high";
		public static final String COLUMN_NAME_SCORE_MID = "score_mid";
		public static final String COLUMN_NAME_SCORE_LOW = "score_low";
		public static final String COLUMN_NAME_SCORE_PYRAMID = "score_pyramid";
		public static final String COLUMN_NAME_LOAD_FLOOR = "load_floor";
		public static final String COLUMN_NAME_LOAD_PLAYER = "load_player";
		public static final String COLUMN_NAME_LOAD_PRELOAD = "load_preload";
		public static final String COLUMN_NAME_DISC_CARRY = "disc_carry";
		public static final String COLUMN_NAME_MAX_HEIGHT = "max_height";
		public static final String COLUMN_NAME_TIMESTAMP = "timestamp";
	}

	public static abstract class WHEEL_BASE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_base_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_BASE_DESC = "wheel_base_desc";
	}

	public static abstract class WHEEL_TYPE_LU_Entry implements BaseColumns {
		public static final String TABLE_NAME = "wheel_type_lu";
		public static final String COLUMN_NAME_ID = "id";
		public static final String COLUMN_NAME_WHEEL_TYPE_DESC = "wheel_type_desc";
	}


	public static final String SQL_CREATE_ENTRIES = 		"SET SQL_MODE=\"NO_AUTO_VALUE_ON_ZERO\";\n" + 
		"SET time_zone = \"+00:00\";\n" + 
		"\n" + 
		"/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n" + 
		"/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n" + 
		"/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n" + 
		"/*!40101 SET NAMES utf8 */;\n" + 
		"\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `configuration_lu` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `configuration_desc` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=8 ;\n" + 
		"\n" + 
		"INSERT INTO `configuration_lu` (`id`, `configuration_desc`) VALUES\n" + 
		"(1, 'Wide'),\n" + 
		"(2, 'Long'),\n" + 
		"(3, 'Square'),\n" + 
		"(4, 'Round'),\n" + 
		"(5, 'Hex'),\n" + 
		"(6, 'Triangle'),\n" + 
		"(7, 'Other');\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `event_lu` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `event_name` varchar(40) COLLATE latin1_general_cs NOT NULL,\n" + 
		"  `match_url` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`),\n" + 
		"  UNIQUE KEY `event_name` (`event_name`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=86 ;\n" + 
		"\n" + 
		"INSERT INTO `event_lu` (`id`, `event_name`, `match_url`) VALUES\n" + 
		"(1, 'Chesapeake Regional', 'http://www2.usfirst.org/2013comp/events/MDBA/ScheduleQual.html'),\n" + 
		"(57, 'Midwest Regional', 'http://www2.usfirst.org/2013comp/Events/ILCH/ScheduleQual.html'),\n" + 
		"(54, 'Silicon Valley Regional', 'http://www2.usfirst.org/2013comp/Events/CASJ/ScheduleQual.html'),\n" + 
		"(4, 'Buckeye Regional', 'http://www2.usfirst.org/2013comp/Events/OHCL/ScheduleQual.html'),\n" + 
		"(52, 'Western Canadian Regional', 'http://www2.usfirst.org/2013comp/Events/ABCA/ScheduleQual.html'),\n" + 
		"(55, 'Colorado Regional', 'http://www2.usfirst.org/2013comp/Events/CODE/ScheduleQual.html'),\n" + 
		"(56, 'Hawaii Regional', 'http://www2.usfirst.org/2013comp/Events/HIHO/ScheduleQual.html'),\n" + 
		"(53, 'Razorback Regional', 'http://www2.usfirst.org/2013comp/Events/ARFA/ScheduleQual.html'),\n" + 
		"(50, 'Alamo Regional', 'http://www2.usfirst.org/2013comp/Events/TXSA/ScheduleQual.html'),\n" + 
		"(51, 'Seattle Regional', 'http://www2.usfirst.org/2013comp/Events/WASE/ScheduleQual.html'),\n" + 
		"(48, 'Oklahoma Regional', 'http://www2.usfirst.org/2013comp/Events/OKOK/ScheduleQual.html'),\n" + 
		"(49, 'Smoky Mountains Regional', 'http://www2.usfirst.org/2013comp/Events/TNKN/ScheduleQual.html'),\n" + 
		"(7, 'Palmetto Regional', 'http://www2.usfirst.org/2013comp/Events/SCMB/ScheduleQual.html'),\n" + 
		"(8, 'Granite State Regional', 'http://www2.usfirst.org/2013comp/Events/NHMA/ScheduleQual.html'),\n" + 
		"(9, 'Finger Lakes Regional', 'http://www2.usfirst.org/2013comp/Events/NYRO/ScheduleQual.html'),\n" + 
		"(10, 'Hub City Regional', 'http://www2.usfirst.org/2013comp/Events/TXLU/ScheduleQual.html'),\n" + 
		"(11, 'Central Valley Regional', 'http://www2.usfirst.org/2013comp/Events/CAMA/ScheduleQual.html'),\n" + 
		"(12, 'Greater Toronto East Regional', 'http://www2.usfirst.org/2013comp/Events/ONTO/ScheduleQual.html'),\n" + 
		"(13, 'San Diego Regional', 'http://www2.usfirst.org/2013comp/Events/CASD/ScheduleQual.html'),\n" + 
		"(14, 'Orlando Regional', 'http://www2.usfirst.org/2013comp/Events/FLOR/ScheduleQual.html'),\n" + 
		"(15, 'WPI Regional', 'http://www2.usfirst.org/2013comp/Events/MAWO/ScheduleQual.html'),\n" + 
		"(16, 'Lake Superior Regional', 'http://www2.usfirst.org/2013comp/Events/MNDU/ScheduleQual.html'),\n" + 
		"(17, 'Northern Lights Regional', 'http://www2.usfirst.org/2013comp/Events/MNDU2/ScheduleQual.html'),\n" + 
		"(18, 'New York City Regional', 'http://www2.usfirst.org/2013comp/Events/NYNY/ScheduleQual.html'),\n" + 
		"(19, 'Oregon Regional', 'http://www2.usfirst.org/2013comp/Events/ORPO/ScheduleQual.html'),\n" + 
		"(20, 'Lone Star Regional', 'http://www2.usfirst.org/2013comp/Events/TXHO/ScheduleQual.html'),\n" + 
		"(21, 'Israel Regional', 'http://www2.usfirst.org/2013comp/Events/ISTA/ScheduleQual.html'),\n" + 
		"(22, 'Montreal Regional', 'http://www2.usfirst.org/2013comp/Events/QCMO/ScheduleQual.html'),\n" + 
		"(23, 'Peachtree Regional', 'http://www2.usfirst.org/2013comp/Events/GADU/ScheduleQual.html'),\n" + 
		"(24, 'Boilermaker Regional', 'http://www2.usfirst.org/2013comp/Events/INWL/ScheduleQual.html'),\n" + 
		"(25, 'Greater Kansas City Regional', 'http://www2.usfirst.org/2013comp/Events/MOKC/ScheduleQual.html'),\n" + 
		"(26, 'St. Louis Regional', 'http://www2.usfirst.org/2013comp/Events/MOSL/ScheduleQual.html'),\n" + 
		"(27, 'North Carolina Regional', 'http://www2.usfirst.org/2013comp/Events/NCRE/ScheduleQual.html'),\n" + 
		"(28, 'Pittsburgh Regional', 'http://www2.usfirst.org/2013comp/Events/PAPI/ScheduleQual.html'),\n" + 
		"(29, 'Virginia Regional', 'http://www2.usfirst.org/2013comp/Events/VARI/ScheduleQual.html'),\n" + 
		"(30, 'Waterloo Regional', 'http://www2.usfirst.org/2013comp/Events/ONWA/ScheduleQual.html'),\n" + 
		"(31, 'Phoenix Regional', 'http://www2.usfirst.org/2013comp/Events/AZCH/ScheduleQual.html'),\n" + 
		"(32, 'Sacramento Regional', 'http://www2.usfirst.org/2013comp/Events/CASA/ScheduleQual.html'),\n" + 
		"(33, 'Los Angeles Regional', 'http://www2.usfirst.org/2013comp/Events/CALB/ScheduleQual.html'),\n" + 
		"(34, 'Bayou Regional', 'http://www2.usfirst.org/2013comp/Events/LAKE/ScheduleQual.html'),\n" + 
		"(35, 'Boston Regional', 'http://www2.usfirst.org/2013comp/Events/MABO/ScheduleQual.html'),\n" + 
		"(36, 'Queen City Regional', 'http://www2.usfirst.org/2013comp/Events/OHIC/ScheduleQual.html'),\n" + 
		"(37, 'Dallas Regional', 'http://www2.usfirst.org/2013comp/Events/TXDA/ScheduleQual.html'),\n" + 
		"(38, 'Utah Regional', 'http://www2.usfirst.org/2013comp/Events/UTWV/ScheduleQual.html'),\n" + 
		"(39, 'Central Washington Regional', 'http://www2.usfirst.org/2013comp/Events/WASE2/ScheduleQual.html'),\n" + 
		"(40, 'Wisconsin Regional', 'http://www2.usfirst.org/2013comp/Events/WIMI/ScheduleQual.html'),\n" + 
		"(41, 'Greater Toronto West Regional', 'http://www2.usfirst.org/2013comp/Events/ONTO2/ScheduleQual.html'),\n" + 
		"(42, 'Inland Empire Regional', 'http://www2.usfirst.org/2013comp/Events/CASB/ScheduleQual.html'),\n" + 
		"(43, 'Connecticut Regional', 'http://www2.usfirst.org/2013comp/Events/CTHA/ScheduleQual.html'),\n" + 
		"(44, 'Washington DC Regional', 'http://www2.usfirst.org/2013comp/Events/DCWA/ScheduleQual.html'),\n" + 
		"(45, 'South Florida Regional', 'http://www2.usfirst.org/2013comp/Events/FLBR/ScheduleQual.html'),\n" + 
		"(46, 'Minnesota 10000 Lakes Regional', 'http://www2.usfirst.org/2013comp/Events/MNMI/ScheduleQual.html'),\n" + 
		"(47, 'Minnesota North Star Regional', 'http://www2.usfirst.org/2013comp/Events/MNMI2/ScheduleQual.html'),\n" + 
		"(58, 'Crossroads Regional', 'http://www2.usfirst.org/2013comp/Events/INTH/ScheduleQual.html'),\n" + 
		"(59, 'Pine Tree Regional', 'http://www2.usfirst.org/2013comp/Events/MELE/ScheduleQual.html'),\n" + 
		"(60, 'Las Vegas Regional', 'http://www2.usfirst.org/2013comp/Events/NVLV/ScheduleQual.html'),\n" + 
		"(61, 'Long Island Regional', 'http://www2.usfirst.org/2013comp/Events/NYLI/ScheduleQual.html'),\n" + 
		"(62, 'Spokane Regional', 'http://www2.usfirst.org/2013comp/Events/WACH/ScheduleQual.html'),\n" + 
		"(63, 'Michigan State Championship', 'http://www2.usfirst.org/2013comp/Events/MICMP/ScheduleQual.html'),\n" + 
		"(64, 'Mid-Atlantic Championship', 'http://www2.usfirst.org/2013comp/Events/MRCMP/ScheduleQual.html'),\n" + 
		"(65, 'Kettering University District', 'http://www2.usfirst.org/2013comp/Events/MIKET/ScheduleQual.html'),\n" + 
		"(66, 'Traverse City District', 'http://www2.usfirst.org/2013comp/Events/MITVC/ScheduleQual.html'),\n" + 
		"(67, 'Hatboro-Horsham District', 'http://www2.usfirst.org/2013comp/Events/PAHAT/ScheduleQual.html'),\n" + 
		"(68, 'Gull Lake District', 'http://www2.usfirst.org/2013comp/Events/MIGUL/ScheduleQual.html'),\n" + 
		"(69, 'Waterford District', 'http://www2.usfirst.org/2013comp/Events/MIWFD/ScheduleQual.html'),\n" + 
		"(70, 'Detroit District', 'http://www2.usfirst.org/2013comp/Events/MIDET/ScheduleQual.html'),\n" + 
		"(71, 'St Joseph District', 'http://www2.usfirst.org/2013comp/Events/MISJO/ScheduleQual.html'),\n" + 
		"(72, 'TCNJ District', 'http://www2.usfirst.org/2013comp/Events/NJEWN/ScheduleQual.html'),\n" + 
		"(73, 'Springside - Chestnut Hill District', 'http://www2.usfirst.org/2013comp/Events/PAPHI/ScheduleQual.html'),\n" + 
		"(74, 'West Michigan District', 'http://www2.usfirst.org/2013comp/Events/MIWMI/ScheduleQual.html'),\n" + 
		"(75, 'Grand Blanc District', 'http://www2.usfirst.org/2013comp/Events/MIGBL/ScheduleQual.html'),\n" + 
		"(76, 'Mount Olive District', 'http://www2.usfirst.org/2013comp/Events/NJFLA/ScheduleQual.html'),\n" + 
		"(77, 'Lenape Seneca District', 'http://www2.usfirst.org/2013comp/Events/NJLEN/ScheduleQual.html'),\n" + 
		"(78, 'Livonia District', 'http://www2.usfirst.org/2013comp/Events/MILIV/ScheduleQual.html'),\n" + 
		"(79, 'Troy District', 'http://www2.usfirst.org/2013comp/Events/MITRY/ScheduleQual.html'),\n" + 
		"(80, 'Bedford District', 'http://www2.usfirst.org/2013comp/Events/MIBED/ScheduleQual.html'),\n" + 
		"(81, 'Bridgewater-Raritan District', 'http://www2.usfirst.org/2013comp/Events/NJBRG/ScheduleQual.html'),\n" + 
		"(82, 'Championship - Archimedes', 'http://www2.usfirst.org/2012comp/Events/Archimedes/ScheduleQual.html'),\n" + 
		"(83, 'Championship - Curie', 'http://www2.usfirst.org/2012comp/Events/Curie/ScheduleQual.html'),\n" + 
		"(84, 'Championship - Galileo', 'http://www2.usfirst.org/2012comp/Events/Galileo/ScheduleQual.html'),\n" + 
		"(85, 'Championship - Newton', 'http://www2.usfirst.org/2012comp/Events/Newton/ScheduleQual.html');\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `fact_match_data` (\n" + 
		"  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `event_id` int(5) unsigned NOT NULL,\n" + 
		"  `match_id` int(3) unsigned NOT NULL,\n" + 
		"  `team_id` int(5) unsigned NOT NULL,\n" + 
		"  `auto_score_high` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_high_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_mid_left` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_mid_left_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_mid_right` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_mid_right_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_low` int(3) unsigned NOT NULL,\n" + 
		"  `auto_score_low_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `score_high` int(3) unsigned NOT NULL,\n" + 
		"  `score_high_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `score_mid_left` int(3) unsigned NOT NULL,\n" + 
		"  `score_mid_left_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `score_mid_right` int(3) unsigned NOT NULL,\n" + 
		"  `score_mid_right_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `score_low` int(3) unsigned NOT NULL,\n" + 
		"  `score_low_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `score_pyramid` int(3) unsigned NOT NULL,\n" + 
		"  `score_pyramid_attempt` int(3) unsigned NOT NULL,\n" + 
		"  `pyramid_level_climbed` int(3) unsigned NOT NULL,\n" + 
		"  `pyramid_attempted` int(3) unsigned NOT NULL,\n" + 
		"  `penalty` tinyint(1) unsigned NOT NULL,\n" + 
		"  `mpenalty` tinyint(1) unsigned NOT NULL,\n" + 
		"  `tip_over` tinyint(1) unsigned NOT NULL,\n" + 
		"  `yellow_card` tinyint(1) unsigned NOT NULL,\n" + 
		"  `red_card` tinyint(1) unsigned NOT NULL,\n" + 
		"  `notes` varchar(1024) COLLATE latin1_general_cs NOT NULL,\n" + 
		"  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" + 
		"  PRIMARY KEY (`id`),\n" + 
		"  KEY `event_index` (`event_id`),\n" + 
		"  KEY `team_index` (`team_id`),\n" + 
		"  KEY `match_id` (`match_id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=0 ;\n" + 
		"\n" + 
		"\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `notes_options` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `option_text` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=4 ;\n" + 
		"\n" + 
		"INSERT INTO `notes_options` (`id`, `option_text`) VALUES\n" + 
		"(1, 'No Show'),\n" + 
		"(2, 'Non-functional'),\n" + 
		"(3, 'Defender');\n" + 
		"\n" + 
		"\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `robot_lu` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `team_id` int(5) unsigned NOT NULL,\n" + 
		"  `robot_photo` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`),\n" + 
		"  KEY `team_id` (`team_id`)\n" + 
		") ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;\n" + 
		"\n" + 
		"\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `scout_pit_data` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `team_id` int(10) unsigned NOT NULL,\n" + 
		"  `configuration_id` int(10) unsigned NOT NULL,\n" + 
		"  `wheel_type_id` int(10) unsigned NOT NULL,\n" + 
		"  `wheel_base_id` int(10) unsigned NOT NULL,\n" + 
		"  `autonomous_mode` tinyint(1) NOT NULL,\n" + 
		"  `scout_comments` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  `pyramid_climb_level` int(3) NOT NULL,\n" + 
		"  `score_high` tinyint(1) NOT NULL,\n" + 
		"  `score_mid` tinyint(1) NOT NULL,\n" + 
		"  `score_low` tinyint(1) NOT NULL,\n" + 
		"  `score_pyramid` tinyint(1) NOT NULL,\n" + 
		"  `load_floor` tinyint(1) NOT NULL,\n" + 
		"  `load_player` tinyint(1) NOT NULL,\n" + 
		"  `load_preload` int(3) NOT NULL,\n" + 
		"  `disc_carry` int(3) NOT NULL,\n" + 
		"  `max_height` int(10) unsigned NOT NULL,\n" + 
		"  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n" + 
		"  PRIMARY KEY (`id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=0 ;\n" + 
		"\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `wheel_base_lu` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `wheel_base_desc` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=9 ;\n" + 
		"\n" + 
		"INSERT INTO `wheel_base_lu` (`id`, `wheel_base_desc`) VALUES\n" + 
		"(1, '2 Wheel Drive'),\n" + 
		"(2, '4 Wheel Drive'),\n" + 
		"(3, '6 Wheel Drive'),\n" + 
		"(5, 'Crab Drive'),\n" + 
		"(6, 'Swerve Drive'),\n" + 
		"(7, 'Tank Drive'),\n" + 
		"(8, 'Other'),\n" + 
		"(4, '8 Wheel Drive (or more)');\n" + 
		"\n" + 
		"CREATE TABLE IF NOT EXISTS `wheel_type_lu` (\n" + 
		"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n" + 
		"  `wheel_type_desc` text COLLATE latin1_general_cs NOT NULL,\n" + 
		"  PRIMARY KEY (`id`)\n" + 
		") ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs AUTO_INCREMENT=11 ;\n" + 
		"\n" + 
		"INSERT INTO `wheel_type_lu` (`id`, `wheel_type_desc`) VALUES\n" + 
		"(1, 'Kit Wheels'),\n" + 
		"(2, 'IFI'),\n" + 
		"(3, 'Omni'),\n" + 
		"(4, 'Mecanum'),\n" + 
		"(5, 'Nylon'),\n" + 
		"(6, 'Rubber'),\n" + 
		"(7, 'Tank Tread'),\n" + 
		"(8, 'Swerve'),\n" + 
		"(9, 'Custom'),\n" + 
		"(10, 'Pneumatic');\n" + 
		"\n" + 
		"/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n" + 
		"/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n" + 
		"/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;";

	public static final String SQL_DELETE_ENTRIES = 
		"DROP TABLE IF EXISTS 'configuration_lu'\n" +
		"DROP TABLE IF EXISTS 'event_lu'\n" +
		"DROP TABLE IF EXISTS 'fact_match_data'\n" +
		"DROP TABLE IF EXISTS 'notes_options'\n" +
		"DROP TABLE IF EXISTS 'robot_lu'\n" +
		"DROP TABLE IF EXISTS 'scout_pit_data'\n" +
		"DROP TABLE IF EXISTS 'wheel_base_lu'\n" +
		"DROP TABLE IF EXISTS 'wheel_type_lu'";

}
